# 1. NUMPY BASICS
- Numpy는 선형대수 라이브러리로 다차원 배열과 조작에 사용된다. 
- Numpy는 두 가지 차원에서 최고의 효율을 낸다. 
    1. Numpy는 프로그래밍 언어 C로 구현되었기 때문에 매우 빠르다.
    2. Numpy는 C구현 되었지만, 사용은 Python 언어로 하기 때문에 매우 강력하다.

In [1]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 

import numpy as np 
# Let's define a one-dimensional array 
my_list = [10, 20, 50, 60, 70]
my_list

[10, 20, 50, 60, 70]

In [2]:
# Let's create a numpy array from the list "my_list"
x = np.array(my_list)
x

array([10, 20, 50, 60, 70])

In [3]:
type(x)

numpy.ndarray

In [4]:
# Multi-dimensional (Matrix definition) 
matrix = np.array([[5, 8], [9, 13]])
matrix

array([[ 5,  8],
       [ 9, 13]])

In [5]:
type(matrix)

numpy.ndarray

**MINI CHALLENGE #1:** 
- **Write a code that creates the following 2x4 numpy array**

```
[[4 6 8 7] 
[20 5 6 9]]
```

In [6]:
# answer
import numpy as np 

my_matrix = np.array([[4, 5, 8, 7], [20, 5, 6, 9]])
my_matrix

array([[ 4,  5,  8,  7],
       [20,  5,  6,  9]])

# 2. BUILT-IN METHODS AND FUNCTIONS 
- rand() - 균일 분포 0에서 1사이에서 수행하는 데에 쓰인다.
- randn() - 표준 정규 분포에서 난수를 생성하는데 쓰인다.
- randint() - 임의의 정수를 생성할 때 사용한다. 
- arange() - 일정한 간격으로 나열된 난수의 배열을 구할 때 사용
- eye() - 대각 행렬 (대각선 방향으로 1생성)을 생성할 때 사용 -> 공분산 행렬에 사용
- ones() - 1로 된 배열을 만들 때 사용 
- zeros() - 0으로 된 배열을 만들 때 사용 

In [7]:
# "rand()" uniform distribution between 0 and 1 
x = np.random.rand(15)
x

array([0.4201188 , 0.69689586, 0.3890583 , 0.92116259, 0.3623641 ,
       0.6148806 , 0.40230633, 0.2285334 , 0.22038665, 0.30088999,
       0.36176674, 0.87656667, 0.51307995, 0.48740983, 0.97123368])

In [8]:
# you can create a matrix of random number as well
x = np.random.rand(5, 5)
x

array([[0.96608759, 0.30457547, 0.25107728, 0.22224539, 0.0079499 ],
       [0.1292588 , 0.33141488, 0.80286231, 0.05380216, 0.32202712],
       [0.07980252, 0.51173707, 0.26342932, 0.89593431, 0.6889833 ],
       [0.59357074, 0.00976064, 0.67063163, 0.44050017, 0.66474385],
       [0.04949097, 0.70058712, 0.10316602, 0.47200387, 0.42782502]])

In [9]:
# "randn()" normal distribution between 0 and 1
x = np.random.randn(10)
x

array([ 0.3266423 , -1.62081606, -1.11455844,  1.06494461,  1.14356113,
        0.71802942, -2.92077518,  0.93460418,  0.24085574,  0.4377186 ])

In [11]:
# "randint" is used to generate random integers between upper and lower bounds
x = np.random.randint(1, 10)
x

5

In [12]:
# "randint" can be used to generate a certain number of random itegers as follows
x = np.random.randint(1, 100, 15)
x

array([10, 51, 72, 95, 51, 97,  5, 82, 51, 81, 99, 60, 35, 18, 97])

In [13]:
# np.arange creates an evenly spaced values within a given interval
x = np.arange(1, 50)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [14]:
# Create an evenly spaced values with a step of 5
x = np.arange(1, 50, 5)   # 1 부터 50까지 범위중 5씩 증가
x

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [15]:
# create a diagonal of ones and zeros everywhere else
x = np.eye(15)
x

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [16]:
# Array of ones
x = np.ones(10)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
# Matrices of ones
x = np.ones((15, 15))
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.

In [19]:
# Array of zeros
x = np.zeros(15)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
# Array of zeros
x = np.zeros((15, 15))
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.

**MINI CHALLENGE #2:**
- **Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x**

In [25]:
# answer
import numpy as np
x = int(input("Please enter a positive integer value: "))

result = np.random.randint(1, x, 20)
result

Please enter a positive integer value: 40


array([19, 18, 29, 36,  7, 36, 21, 26, 11, 15, 39, 10, 27, 39, 31, 17,  2,
        2,  8, 18])

# 3. SHAPE, LENGTH, TYPE, RESHAPE, AND MAX/MIN VALUES

In [28]:
# Let's define a one-dimensional array 
# 1차원 배열 

my_list = [-30, 4, 50, 60, 29, 15, 22, 90]
print(my_list)
x = np.array(my_list)
x

[-30, 4, 50, 60, 29, 15, 22, 90]


array([-30,   4,  50,  60,  29,  15,  22,  90])

In [29]:
# Get Length of a numpy array
len(x)

8

In [30]:
# Get shape - 넘파이 배열의 차원 구하기
x.shape

(8,)

In [31]:
# Obtain the datatype
x.dtype

dtype('int64')

In [33]:
# Reshape 1D array into a matrix
# 차원 변경 - 1차원 배열을 2x4 행렬로 만들기 
z = x.reshape(2, 4)
z

array([[-30,   4,  50,  60],
       [ 29,  15,  22,  90]])

In [34]:
# Obtain the maximum element (value)
# 넘파일 배열의 최댓값 구하기
x.max()

90

In [35]:
# Obtain the minimum element (value)
# 넘파일 배열의 최소값 구하기
x.min()

-30

In [36]:
# Obtain the location of the max element
# 넘파일 배열의 최댓값 위치 구하기 
x.argmax()

7

In [37]:
# Obtain the location of the min element
# 넘파일 배열의 최소값 위치 구하기
x.argmin()

0

**MINI CHALLENGE #3:**
- **Write a code that creates a 4x5 array inwhich numbers range between 300 and 500 such that the difference between elements is 10**

In [50]:
# answer
import numpy as np 

x = np.arange(300, 500, 10)
x = x.reshape(4, 5)
x

array([[300, 310, 320, 330, 340],
       [350, 360, 370, 380, 390],
       [400, 410, 420, 430, 440],
       [450, 460, 470, 480, 490]])

**MINI CHALLENGE #4:**
- **Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values** 

In [56]:
# answer
import numpy as np 

arr = np.random.randint(-1000, 1000, size=(20, 20))
print(arr.shape)            # 배열 길이
print(arr.max())            # 배열 최대값
print(arr.min())            # 배열 최소값
print(arr.mean())           # 배열 평균값

(20, 20)
987
-995
-9.9775


In [58]:
# 깔끔하게 적어보자 
print(f"The maximum value is: {arr.max()} and the minimum value is: {arr.min()} and the mean value is: {arr.mean()}")

The maximum value is: 987 and the minimum value is: -995 and the mean value is: -9.9775


# 4. MATHEMATICAL OPERATIONS

In [60]:
# np.arange() returns an evenly spaced values within a given interval
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
y = np.arange(1, 10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
# Add 2 numpy arrays together
sum_array = x + y
sum_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [63]:
# arrays squared
squared = x ** 2
squared

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [65]:
# array square root(제곱근)
sqrt = np.sqrt(squared)
sqrt

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [66]:
# array obtain (넘파이 배열의 지수 - Numpy exponential)
z = np.exp(y)
z 

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

**MINI CHALLENGE #5:**
- **Given the X and Y values below, obtain the distance between them**


```
X = [3, 20, 30]
Y = [4, 6, 7]
```

In [68]:
# answer
# 각 요소를 제곱한 후 더하기, 그런 다음 제곱해서 더한 요소의 제곱근을 구해준다.
x = np.array([3, 20, 30])
y = np.array([4, 6, 7])

z = np.array(x**2 + y**2)
z = np.sqrt(z)
z

array([ 5.        , 20.88061302, 30.8058436 ])

# 5. SLICING AND INDEXING 

In [69]:
x = np.array([20, 40, 50, 21, 15])
x

array([20, 40, 50, 21, 15])

In [72]:
# Access specific index from the numpy array
x[0]

20

In [73]:
# Starting from the first index 0 up until and NOT inlcluding the last element
x[0:3]

array([20, 40, 50])

In [74]:
# Broadcasting, altering several values in a numpy array at once
x[0:2] = 10
x

array([10, 10, 50, 21, 15])

In [75]:
# Let's define a two dimensional numpy array
martrix = np.random.randint(1, 10, (5, 5))
martrix

array([[3, 8, 1, 6, 3],
       [2, 8, 3, 6, 8],
       [2, 7, 3, 6, 5],
       [6, 2, 5, 7, 2],
       [6, 3, 8, 5, 6]])

In [78]:
# Get a row from a mtrix
martrix[2]

array([2, 7, 3, 6, 5])

In [81]:
martrix[0]

array([3, 8, 1, 6, 3])

In [80]:
# Get one element
martrix[0][2]

1

In [83]:
martrix[2][3]

6

In [88]:
martrix

array([[3, 8, 1, 6, 3],
       [2, 8, 3, 6, 8],
       [2, 7, 3, 6, 5],
       [6, 2, 5, 7, 2],
       [6, 3, 8, 5, 6]])

In [85]:
mini_matrix = martrix[:4]
mini_matrix

array([[3, 8, 1, 6, 3],
       [2, 8, 3, 6, 8],
       [2, 7, 3, 6, 5],
       [6, 2, 5, 7, 2]])

In [86]:
mini_matrix = martrix[:, 2:]
mini_matrix

array([[1, 6, 3],
       [3, 6, 8],
       [3, 6, 5],
       [5, 7, 2],
       [8, 5, 6]])

In [87]:
mini_matrix = martrix[:, :2]
mini_matrix

array([[3, 8],
       [2, 8],
       [2, 7],
       [6, 2],
       [6, 3]])

**MINI CHALLENGE #6:**
- **In the following matrix, replace the last row with -1**
- **Multiply the 2x2 matrix in the upper right corner by 2**



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



In [102]:
# answer - solution 1
x = np.random.randint(-10, 100, (5, 5))
x[4:5, 4:5] = -1
x

array([[  6,   3,  35,  15,  97],
       [ -4,  90,  63,  29,  74],
       [ -6, -10,  99,   3,  75],
       [ 95,   7,  65,  14,  54],
       [ -4,  25,  70,  19,  -1]])

In [110]:
x[:2, 3:] = x[:2, 3:]**2
x

array([[   6,    3,   35,  225, 9409],
       [  -4,   90,   63,  841, 5476],
       [  -6,  -10,   99,    3,   75],
       [  95,    7,   65,   14,   54],
       [  -4,   25,   70,   19,   -1]])

In [114]:
# answer - asolution 2
x = np.array([[2, 30, 20, -2, -4],
             [3, 4,  40, -3, -2],
             [-3, 4, -6, 90, 10],
             [25, 45, 34, 22, 12],
             [13, 24, 22, 32, 37]])
x

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [13, 24, 22, 32, 37]])

In [116]:
x[4] = -1
x

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [-1, -1, -1, -1, -1]])

In [117]:
x[:2, 3:] = x[:2, 3:] * 2
x

array([[ 2, 30, 20, -4, -8],
       [ 3,  4, 40, -6, -4],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [-1, -1, -1, -1, -1]])

# 6. ELEMENTS SELECTION (CONDITIONAL)

In [120]:
matrix = np.random.randint(1, 10, (5, 5))
matrix

array([[6, 5, 7, 4, 9],
       [5, 3, 7, 4, 1],
       [7, 7, 4, 2, 9],
       [9, 5, 4, 1, 6],
       [7, 4, 9, 6, 9]])

In [122]:
new_matrix = matrix[matrix > 3]
new_matrix

array([6, 5, 7, 4, 9, 5, 7, 4, 7, 7, 4, 9, 9, 5, 4, 6, 7, 4, 9, 6, 9])

In [123]:
new_matrix = matrix[matrix % 2 == 0]
new_matrix

array([6, 4, 4, 4, 2, 4, 6, 4, 6])

In [124]:
new_matrix = matrix[matrix % 3 == 1]
new_matrix

array([7, 4, 7, 4, 1, 7, 7, 4, 4, 1, 7, 4])

**MINI CHALLENGE #7:**
- **In the following matrix, replace negative elements by 0 and replace odd elements with 25**


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [125]:
# answer
x = np.array([[2, 30, 20, -2, -4],
             [3, 4,  40, -3, -2],
             [-3, 4, -6, 90, 10],
             [25, 45, 34, 22, 12],
             [13, 24, 22, 32, 37]])

# replace negative by 0
x[x < 0] = 0
x

array([[ 2, 30, 20,  0,  0],
       [ 3,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [25, 45, 34, 22, 12],
       [13, 24, 22, 32, 37]])

In [126]:
# replace odd with 25
x[x % 3 == 1] = 25
x

array([[ 2, 30, 20,  0,  0],
       [ 3, 25, 25,  0,  0],
       [ 0, 25,  0, 90, 25],
       [25, 45, 25, 25, 12],
       [25, 24, 25, 32, 25]])

# EXCELLENT JOB!